steps:
  - name: "gcr.io/cloud-builders/npm"
    dir: "ui"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm ci
        npm run build

  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -d "ui/dist" ]; then
          gsutil -m rsync -r -d ui/dist "gs://${_UI_BUCKET}"
        else
          gsutil -m rsync -r -d ui/build "gs://${_UI_BUCKET}"
        fi


substitutions:
  _UI_BUCKET: "imc-ui-dev-479617-bucket"

options:
  logging: CLOUD_LOGGING_ONLY
